### ISSUE TITLE
dependencies not installed with 'npm install'

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs-shipyard/station#57] opened 2015-10-12 22:20 UTC
I cloned the repo down and followed the setup instructions and still needed a few things:
- `rimraf`
- `babel`
- electron
  - command not found. I did 'npm install electron' and it still didnt work.

There may be more, but I'm stuck on the electron issue.

**Comment by Dignifiedquire** [comment] 2015-10-12 22:28
Those are all installed but not globally, did you check node_modules/.bin/ ?

also try the scripts advertiesed in the readme i.e `npm start`

**Comment by whyrusleeping** [comment] 2015-10-12 22:53
yeah, i ran:
```
git clone https://github.com/ipfs/station
cd station
npm install
npm start
```

And it failed because rimraf wasnt installed, so i did `npm install rimraf` and ran `npm start` again, then it complained about not having babel installed so i ran `npm installed babel`, then it threw a different error about not having `node_modules/.bin/concurrent` so i ran `npm install concurrently` and ran `npm start` again, and then it complained about not being able to find the binary `electron`, and running `npm install electron` didnt fix that issue.

**Comment by Dignifiedquire** [comment] 2015-10-12 22:57
That's very odd, did the `npm install` throw any errors? What node and npm version and what os are you running?

**Comment by whyrusleeping** [comment] 2015-10-12 23:06
npm version 3.3.6, node version 0.12.2

npm install spat out a couple warnings about how js-beautify should be installed with -g and a couple other similar ones.

And it also says that react-file-drop requires a peer of react, but none was installed. (also a warning).

**Comment by diasdavid** [comment] 2015-10-13 04:01
@whyrusleeping try doing `npm install` with node 4.2.0 (if you use [n](http://npmjs.org/n), just do `n latest`)

**Comment by whyrusleeping** [comment] 2015-10-13 04:23
wait, i need to go from node 0.12.2 to version 4.2.0 ?

**Comment by diasdavid** [comment] 2015-10-13 04:28
@whyrusleeping node 0.12.7, then iojs 1.x.x, 2.x.x, 3.x.x and then back to node in 4.0.0 and how will be node only onwards. Docs for all the versions https://nodejs.org/docs/ (plus vid for more context https://vimeo.com/138937671)

**Comment by bcomnes** [comment] 2015-10-13 04:36
While we are at it though, @whyrusleeping sheds light on an important detail:  the scripts reference .bin paths explicitly!  This is no good since npm hoists `node_modules/.bin` to the front of the $PATH when executing this scripts.  Explicitly targeting these executables is not only more verbose, but possibly gets in the way of letting npm do it's job.

Lets get that fixed real quick.

**Comment by whyrusleeping** [comment] 2015-10-13 04:44
dude, i just cant javascript very well

**Comment by whyrusleeping** [comment] 2015-10-13 05:08
alright, install node 420 and ran npm install and npm start. same issue.

**Comment by whyrusleeping** [comment] 2015-10-13 05:20
deleted the repo, recloned, and got farther:
```
[22:15:47] whyrusleeping@Why-MBP /Users/whyrusleeping/Code/station (0)                                                                                                                      
> npm start

> ipfs-station@1.0.0-alpha.0 start /Users/whyrusleeping/Code/station
> npm run clean && npm run build:babel && ./node_modules/.bin/concurrent --kill-others "node dev-server.js" "npm run electron"


> ipfs-station@1.0.0-alpha.0 clean /Users/whyrusleeping/Code/station
> rimraf build && mkdir build


> ipfs-station@1.0.0-alpha.0 build:babel /Users/whyrusleeping/Code/station
> babel app/config.js -o build/config.js && ./node_modules/.bin/babel app/controls -d build/controls && ./node_modules/.bin/babel app/init.js -o build/init.js && ./node_modules/.bin/babel app/helpers.js -o build/helpers.js

app/controls/drag-drop.js -> build/controls/drag-drop.js
app/controls/open-browser.js -> build/controls/open-browser.js
app/controls/open-console.js -> build/controls/open-console.js
app/controls/open-settings.js -> build/controls/open-settings.js
app/controls/utils.js -> build/controls/utils.js
[1] 
[1] > ipfs-station@1.0.0-alpha.0 electron /Users/whyrusleeping/Code/station
[1] > electron index.js 2>&1
[1] 
[0] Development server started at http://localhost:3000
[1] info: Application is ready
[1] error: uncaughtException: Cannot read property 'Hash' of undefined date=Mon Oct 12 2015 22:16:01 GMT-0700 (PDT), pid=22183, uid=501, gid=20, cwd=/Users/whyrusleeping/Code/station, execPath=/Users/whyrusleeping/Code/station/node_modules/electron-prebuilt/dist/Electron.app/Contents/MacOS/Electron, version=v4.1.1, argv=[/Users/whyrusleeping/Code/station/node_modules/electron-prebuilt/dist/Electron.app/Contents/MacOS/Electron, index.js], rss=64061440, heapTotal=31119120, heapUsed=17424816, loadavg=[3.43359375, 2.19677734375, 1.88916015625], uptime=125599
[1] TypeError: Cannot read property 'Hash' of undefined
[1]     at /Users/whyrusleeping/Code/station/node_modules/ipfs-geoip/ipfs-geoip.js:42:58
[1]     at IncomingMessage.<anonymous> (/Users/whyrusleeping/Code/station/node_modules/ipfs-api/src/request-api.js:89:14)
[1]     at emitNone (events.js:72:20)
[1]     at IncomingMessage.emit (events.js:166:7)
[1]     at endReadableNT (_stream_readable.js:893:12)
[1]     at doNTCallback2 (node.js:441:9)
[1]     at process._tickCallback (node.js:355:17)
[1] 
```

**Comment by Dignifiedquire** [comment] 2015-10-13 06:43
That sounds like a bug in https://github.com/ipfs/ipfs-geoip but I'm totally unclear as to why that only happens on your machine and not on mine. Stupid question, did you stop your ipfs daemon before?

**Comment by Dignifiedquire** [comment] 2015-10-13 06:44
@bcomnes I'm sorry I'm not seeing how referencing `node_modules/.bin` is more verbose than referencing `node_modules/module-name/path/to/bin`.

**Comment by bcomnes** [comment] 2015-10-14 01:30
npm adds `node_modules/.bin` to the PATH during the execution of npm scripts. so you don't need to add that in the script itself.  Simply reference the tool in `.bin` as if it were in your path.  That being said, I was having issues with the prod script and npm not finding these in its path.  I dont understand whats going on yet.

**Comment by Dignifiedquire** [comment] 2015-10-14 08:02
Okay, so the issue with that is yes it works most of the times, but I had a lot of issues with this assumption especially with `npm@2` where this would simply not work and I had to install these globally to solve the issue.

**Comment by Dignifiedquire** [comment] 2015-10-14 08:02
@whyrusleeping did you get any further?

**Comment by VictorBjelkholm** [comment] 2015-10-18 17:36
Just cloned the repo and can reproduce this with the same steps.

Full output
```
➜  station git:(master) npm start

> ipfs-station@1.0.0-alpha.0 start /Users/victor/Projects/station
> npm run clean && npm run build:babel && ./node_modules/.bin/concurrent --kill-others "node dev-server.js" "npm run electron"


> ipfs-station@1.0.0-alpha.0 clean /Users/victor/Projects/station
> rimraf build && mkdir build


> ipfs-station@1.0.0-alpha.0 build:babel /Users/victor/Projects/station
> babel app/config.js -o build/config.js && ./node_modules/.bin/babel app/controls -d build/controls && ./node_modules/.bin/babel app/init.js -o build/init.js && ./node_modules/.bin/babel app/helpers.js -o build/helpers.js

app/controls/drag-drop.js -> build/controls/drag-drop.js
app/controls/open-browser.js -> build/controls/open-browser.js
app/controls/open-console.js -> build/controls/open-console.js
app/controls/open-settings.js -> build/controls/open-settings.js
app/controls/utils.js -> build/controls/utils.js
[0] Development server started at http://localhost:3000
[1]
[1] > ipfs-station@1.0.0-alpha.0 electron /Users/victor/Projects/station
[1] > electron index.js 2>&1
[1]
[1] info: Booting
[1] info: Application is ready
[1] info: Starting tray
[1] Uncaught TypeError: Cannot read property 'Hash' of undefined
[1]     at <error: TypeError: Cannot read property 'name' of undefined>
[1]     at <error: TypeError: Cannot read property 'name' of undefined>
[1]     at <error: TypeError: Cannot read property 'name' of undefined>
[1]     at <error: TypeError: Cannot read property 'name' of undefined>
[1]     at <error: TypeError: Cannot read property 'name' of undefined>
[1]     at <error: TypeError: Cannot read property 'name' of undefined>
[1]     at <error: TypeError: Cannot read property 'name' of undefined>
[1]     at <error: TypeError: Cannot read property 'name' of undefined>
[1]     at <error: TypeError: Cannot read property 'name' of undefined>
[1] ----------------------------------------
[1]     at EventEmitter.on
[1]     at makeWrappedCallback (/Users/victor/Projects/station/node_modules/long-stack-traces/lib/long-stack-traces.js:65:26)
[1]     at IncomingMessage.object.(anonymous function) [as on] (/Users/victor/Projects/station/node_modules/long-stack-traces/lib/long-stack-traces.js:51:38)
[1]     at IncomingMessage.Readable.on (_stream_readable.js:655:33)
[1]     at ClientRequest.<anonymous> (/Users/victor/Projects/station/node_modules/ipfs-api/src/request-api.js:73:9)
[1]     at ClientRequest.g (events.js:260:16)
[1]     at ClientRequest.<anonymous> (/Users/victor/Projects/station/node_modules/long-stack-traces/lib/long-stack-traces.js:76:33)
[1]     at emitOne (events.js:77:13)
[1]     at ClientRequest.emit (events.js:169:7)
[1]     at HTTPParser.parserOnIncomingClient (_http_client.js:415:21)
[1]     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
[1] ----------------------------------------
[1]     at EventEmitter.on
[1]     at makeWrappedCallback (/Users/victor/Projects/station/node_modules/long-stack-traces/lib/long-stack-traces.js:65:26)
[1]     at ClientRequest.object.(anonymous function) [as on] (/Users/victor/Projects/station/node_modules/long-stack-traces/lib/long-stack-traces.js:51:38)
[1]     at ClientRequest.once (events.js:265:8)
[1]     at new ClientRequest (_http_client.js:72:10)
[1]     at Object.exports.request (http.js:31:10)
[1]     at requestAPI (/Users/victor/Projects/station/node_modules/ipfs-api/src/request-api.js:50:18)
[1]     at Object.get (/Users/victor/Projects/station/node_modules/ipfs-api/src/index.js:49:14)
[1]     at _lookup (/Users/victor/Projects/station/node_modules/ipfs-geoip/ipfs-geoip.js:30:15)
[1]     at conf.original (/Users/victor/Projects/station/node_modules/ipfs-geoip/node_modules/memoizee/ext/async.js:103:18)
[1]     at /Users/victor/Projects/station/node_modules/ipfs-geoip/node_modules/memoizee/lib/configure-map.js:43:24
[1] ----------------------------------------
[1]     at EventEmitter.on
[1]     at makeWrappedCallback (/Users/victor/Projects/station/node_modules/long-stack-traces/lib/long-stack-traces.js:65:26)
[1]     at IncomingMessage.object.(anonymous function) [as on] (/Users/victor/Projects/station/node_modules/long-stack-traces/lib/long-stack-traces.js:51:38)
[1]     at IncomingMessage.Readable.on (_stream_readable.js:655:33)
[1]     at ClientRequest.<anonymous> (/Users/victor/Projects/station/node_modules/ipfs-api/src/request-api.js:73:9)
[1]     at ClientRequest.g (events.js:260:16)
[1]     at ClientRequest.<anonymous> (/Users/victor/Projects/station/node_modules/long-stack-traces/lib/long-stack-traces.js:76:33)
[1]     at emitOne (events.js:77:13)
[1]     at ClientRequest.emit (events.js:169:7)
[1]     at HTTPParser.parserOnIncomingClient (_http_client.js:415:21)
[1]     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
[1] ----------------------------------------
[1]     at EventEmitter.on
[1]     at makeWrappedCallback (/Users/victor/Projects/station/node_modules/long-stack-traces/lib/long-stack-traces.js:65:26)
[1]     at ClientRequest.object.(anonymous function) [as on] (/Users/victor/Projects/station/node_modules/long-stack-traces/lib/long-stack-traces.js:51:38)
[1]     at ClientRequest.once (events.js:265:8)
[1]     at new ClientRequest (_http_client.js:72:10)
[1]     at Object.exports.request (http.js:31:10)
[1]     at requestAPI (/Users/victor/Projects/station/node_modules/ipfs-api/src/request-api.js:50:18)
[1]     at IpfsAPI.self.id (/Users/victor/Projects/station/node_modules/ipfs-api/src/index.js:153:12)
[1]     at pollStats (/Users/victor/Projects/station/build/init.js:62:8)
[1]     at /Users/victor/Projects/station/build/init.js:103:5
[1]     at Stream.<anonymous> (/Users/victor/Projects/station/node_modules/ipfsd-ctl/index.js:115:15)
[1] ----------------------------------------
[1]     at EventEmitter.on
[1]     at makeWrappedCallback (/Users/victor/Projects/station/node_modules/long-stack-traces/lib/long-stack-traces.js:65:26)
[1]     at Stream.object.(anonymous function) [as on] (/Users/victor/Projects/station/node_modules/long-stack-traces/lib/long-stack-traces.js:51:38)
[1]     at /Users/victor/Projects/station/node_modules/ipfsd-ctl/index.js:107:12
[1]     at parseConfig (/Users/victor/Projects/station/node_modules/ipfsd-ctl/index.js:165:5)
[1]     at Object.startDaemon (/Users/victor/Projects/station/node_modules/ipfsd-ctl/index.js:93:7)
[1]     at onStartDaemon (/Users/victor/Projects/station/build/init.js:92:8)
[1]     at EventEmitter.<anonymous> (/Users/victor/Projects/station/build/init.js:263:9)
[1]     at EventEmitter.<anonymous> (/Users/victor/Projects/station/node_modules/long-stack-traces/lib/long-stack-traces.js:76:33)
[1]     at emitNone (events.js:67:13)
[1]     at EventEmitter.emit (events.js:166:7)
[1] ----------------------------------------
[1]     at EventEmitter.on
[1]     at makeWrappedCallback (/Users/victor/Projects/station/node_modules/long-stack-traces/lib/long-stack-traces.js:65:26)
[1]     at EventEmitter.object.(anonymous function) [as on] (/Users/victor/Projects/station/node_modules/long-stack-traces/lib/long-stack-traces.js:51:38)
[1]     at /Users/victor/Projects/station/build/init.js:241:8
[1]     at Object.module.exports.local (/Users/victor/Projects/station/node_modules/ipfsd-ctl/index.js:186:5)
[1]     at Object.boot (/Users/victor/Projects/station/build/init.js:236:25)
[1]     at EventEmitter.<anonymous> (/Users/victor/Projects/station/node_modules/long-stack-traces/lib/long-stack-traces.js:76:33)
[1]     at emitOne (events.js:77:13)
[1]     at EventEmitter.emit (events.js:169:7)
[1]     at Server.handleListening (/Users/victor/Projects/station/node_modules/monogamous/dist/monogamous.js:65:23)
[1]     at Server.<anonymous> (/Users/victor/Projects/station/node_modules/long-stack-traces/lib/long-stack-traces.js:76:33)
[1] ----------------------------------------
[1]     at EventEmitter.on
[1]     at makeWrappedCallback (/Users/victor/Projects/station/node_modules/long-stack-traces/lib/long-stack-traces.js:65:26)
[1]     at EventEmitter.object.(anonymous function) [as on] (/Users/victor/Projects/station/node_modules/long-stack-traces/lib/long-stack-traces.js:51:38)
[1]     at Object.<anonymous> (/Users/victor/Projects/station/index.js:29:8)
[1]     at Module._compile (module.js:434:26)
[1]     at Object.Module._extensions..js (module.js:452:10)
[1]     at Module.load (module.js:355:32)
[1]     at Function.Module._load (module.js:310:12)
[1]     at Object.<anonymous> (/Users/victor/Projects/station/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/default_app/main.js:246:23)
[1]     at Module._compile (module.js:434:26)
[1]     at Object.Module._extensions..js (module.js:452:10)
[1] Uncaught undefined
[1] error: Uncaught Exception
[1]
[1] npm ERR! Darwin 15.0.0
[1] npm ERR! argv "/Users/victor/.nvm/versions/node/v4.1.0/bin/node" "/Users/victor/.nvm/versions/node/v4.1.0/bin/npm" "run" "electron"
[1] npm ERR! node v4.1.0
[1] npm ERR! npm  v2.14.3
[1] npm ERR! code ELIFECYCLE
[1] npm ERR! ipfs-station@1.0.0-alpha.0 electron: `electron index.js 2>&1`
[1] npm ERR! Exit status 1
[1] npm ERR!
[1] npm ERR! Failed at the ipfs-station@1.0.0-alpha.0 electron script 'electron index.js 2>&1'.
[1] npm ERR! This is most likely a problem with the ipfs-station package,
[1] npm ERR! not with npm itself.
[1] npm ERR! Tell the author that this fails on your system:
[1] npm ERR!
[1]      electron index.js 2>&1
[1] npm ERR! You can get their info via:
[1] npm ERR!     npm owner ls ipfs-station
[1] npm ERR! There is likely additional logging output above.
[1]
[1] npm ERR! Please include the following file with any support request:
[1] npm ERR!     /Users/victor/Projects/station/npm-debug.log
[1] npm run electron exited with code 1
--> Sending SIGTERM to other processes..
[0] node dev-server.js exited with code null

npm ERR! Darwin 15.0.0
npm ERR! argv "/Users/victor/.nvm/versions/node/v4.1.0/bin/node" "/Users/victor/.nvm/versions/node/v4.1.0/bin/npm" "start"
npm ERR! node v4.1.0
npm ERR! npm  v2.14.3
npm ERR! code ELIFECYCLE
npm ERR! ipfs-station@1.0.0-alpha.0 start: `npm run clean && npm run build:babel && ./node_modules/.bin/concurrent --kill-others "node dev-server.js" "npm run electron"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ipfs-station@1.0.0-alpha.0 start script 'npm run clean && npm run build:babel && ./node_modules/.bin/concurrent --kill-others "node dev-server.js" "npm run electron"'.
npm ERR! This is most likely a problem with the ipfs-station package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run clean && npm run build:babel && ./node_modules/.bin/concurrent --kill-others "node dev-server.js" "npm run electron"
npm ERR! You can get their info via:
npm ERR!     npm owner ls ipfs-station
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/victor/Projects/station/npm-debug.log
```

**Comment by diasdavid** [comment] 2015-10-18 17:58
@VictorBjelkholm try updating your npm to version 3, as @Dignifiedquire said:

> I had a lot of issues with this assumption especially with npm@2 where this would simply not work

**Comment by whyrusleeping** [comment] 2015-10-18 17:58
updated and tried again and got the same error as @VictorBjelkholm

**Comment by whyrusleeping** [comment] 2015-10-18 18:01
removed my `.ipfs` folder and reran it, it worked until i clicked console, at which point it crashed:
```
[0] Development server started at http://localhost:3000
[1] 
[1] > ipfs-station@1.0.0-alpha.0 electron /home/whyrusleeping/code/station
[1] > electron index.js 2>&1
[1] 
[1] info: Booting
[1] info: Application is ready
[1] info: Starting tray
[1] info: Initialzing new node
[0] webpack built b32b02d6473d4516e7c2 in 3210ms
[1] info: Initializing new node with key size: 4096 in /home/whyrusleeping/.ipfs.
[1] Uncaught undefined
[1] Uncaught undefined
[1] error: Uncaught Exception 
[1] 
[1] npm
[1]  ERR!
[1]  Linux 4.2.2-1-ARCH
[1] npm
[1]  ERR! 
[1] argv "/usr/bin/node" "/usr/bin/npm" "run" "electron"
[1] npm
[1]  ERR! node v4.1.2
[1] npm
[1]  ERR! npm  v3.3.6
[1] npm
[1]  ERR! code ELIFECYCLE
[1] npm ERR!
[1]  ipfs-station@1.0.0-alpha.0 electron: `electron index.js 2>&1`
[1] npm ERR! Exit status 1
[1] npm ERR! 
[1] npm ERR! Failed at the ipfs-station@1.0.0-alpha.0 electron script 'electron index.js 2>&1'.
[1] npm
[1]  ERR! This is most likely a problem with the ipfs-station package,
[1] npm ERR! not with npm itself.
[1] npm
[1]  ERR! Tell the author that this fails on your system:
[1] npm ERR!
[1]      electron index.js 2>&1
[1] npm ERR!
[1]  You can get their info via:
[1] npm ERR!     npm owner ls ipfs-station
[1] npm ERR! There is likely additional logging output above.
[1] 
[1] npm
[1]  ERR! Please include the following file with any support request:
[1] npm ERR!     /home/whyrusleeping/code/station/npm-debug.log
[1] npm run electron exited with code 1
--> Sending SIGTERM to other processes..
[0] node dev-server.js exited with code null
```

**Comment by VictorBjelkholm** [comment] 2015-10-18 19:11
Hm, reinstalled npm to version 3.3.8 (although I don't understand why 2.X wouldn't work?) and starts ok but doesn't run. Seems like `socket.io` is missing from **views** somehow... Also, daemon not running, not sure if it's connected with socket.io issue.

```
> ipfs-station@1.0.0-alpha.0 start /Users/victor/Projects/station
> npm run clean && npm run build:babel && ./node_modules/.bin/concurrent --kill-others "node dev-server.js" "npm run electron"


> ipfs-station@1.0.0-alpha.0 clean /Users/victor/Projects/station
> rimraf build && mkdir build


> ipfs-station@1.0.0-alpha.0 build:babel /Users/victor/Projects/station
> babel app/config.js -o build/config.js && ./node_modules/.bin/babel app/controls -d build/controls && ./node_modules/.bin/babel app/init.js -o build/init.js && ./node_modules/.bin/babel app/helpers.js -o build/helpers.js

app/controls/drag-drop.js -> build/controls/drag-drop.js
app/controls/open-browser.js -> build/controls/open-browser.js
app/controls/open-console.js -> build/controls/open-console.js
app/controls/open-settings.js -> build/controls/open-settings.js
app/controls/utils.js -> build/controls/utils.js
[0] Development server started at http://localhost:3000
[1]
[1] > ipfs-station@1.0.0-alpha.0 electron /Users/victor/Projects/station
[1] > electron index.js 2>&1
[1]
[1] info: Booting
[1] info: Application is ready
[1] info: Starting tray
[0] webpack built 0cd2251bcc88096714b6 in 4192ms
[0] Error: ENOENT: no such file or directory, stat '/Users/victor/Projects/station/app/views/socket.io'
[0]     at Error (native)
[0] Error: ENOENT: no such file or directory, stat '/Users/victor/Projects/station/app/views/socket.io'
[0]     at Error (native)
[0] Error: ENOENT: no such file or directory, stat '/Users/victor/Projects/station/app/views/socket.io'
[0]     at Error (native)
[0] Error: ENOENT: no such file or directory, stat '/Users/victor/Projects/station/app/views/socket.io'
[0]     at Error (native)
[0] Error: ENOENT: no such file or directory, stat '/Users/victor/Projects/station/app/views/socket.io'
[0]     at Error (native)
[0] Error: ENOENT: no such file or directory, stat '/Users/victor/Projects/station/app/views/socket.io'
[0]     at Error (native)
[1] [Error: Cannot open console, IPFS daemon not running]
[0] Error: ENOENT: no such file or directory, stat '/Users/victor/Projects/station/app/views/socket.io'
[0]     at Error (native)
[1] [Error: Cannot open browser, IPFS daemon not running]
[1] info: Stopping daemon
[0] Error: ENOENT: no such file or directory, stat '/Users/victor/Projects/station/app/views/socket.io'
[0]     at Error (native)
[0] Error: ENOENT: no such file or directory, stat '/Users/victor/Projects/station/app/views/socket.io'
[0]     at Error (native)
[0] Error: ENOENT: no such file or directory, stat '/Users/victor/Projects/station/app/views/socket.io'
[0]     at Error (native)
[0] Error: ENOENT: no such file or directory, stat '/Users/victor/Projects/station/app/views/socket.io'
[0]     at Error (native)
[0] Error: ENOENT: no such file or directory, stat '/Users/victor/Projects/station/app/views/socket.io'
[0]     at Error (native)
[0] Error: ENOENT: no such file or directory, stat '/Users/victor/Projects/station/app/views/socket.io'
[0]     at Error (native)
[0] Error: ENOENT: no such file or directory, stat '/Users/victor/Projects/station/app/views/socket.io'
[0]     at Error (native)
```

**Comment by diasdavid** [comment] 2015-10-24 05:19
station doesn't stay on for long, crashing for me:

```
> ipfs-station@1.0.0-alpha.1 clean /Users/david/Documents/code/ipfs/station
> rimraf build && mkdir build


> ipfs-station@1.0.0-alpha.1 build:babel /Users/david/Documents/code/ipfs/station
> babel app/config.js -o build/config.js && ./node_modules/.bin/babel app/controls -d build/controls && ./node_modules/.bin/babel app/init.js -o build/init.js && ./node_modules/.bin/babel app/helpers.js -o build/helpers.js

app/controls/drag-drop.js -> build/controls/drag-drop.js
app/controls/open-browser.js -> build/controls/open-browser.js
app/controls/open-console.js -> build/controls/open-console.js
app/controls/open-settings.js -> build/controls/open-settings.js
app/controls/utils.js -> build/controls/utils.js
[0] Development server started at http://localhost:3000
[1]
[1] > ipfs-station@1.0.0-alpha.1 electron /Users/david/Documents/code/ipfs/station
[1] > electron index.js 2>&1
[1]
[1] info: Booting
[1] info: Application is ready
[1] info: Starting tray
[1] info: Initialzing new node
[0] webpack built 65426a7a4fccfe6c22eb in 3572ms
[1] info: Initializing new node with key size: 4096 in /Users/david/.ipfs.
[1] info: Uploading files files=[/Users/david/Desktop/Wine in the morning.jpg]
[1] info: Uploaded file Wine in the morning.jpg
[1] Uncaught undefined
[1] Uncaught undefined
[1] error: Uncaught Exception
[1]
[1] npm
[1]  ERR!
[1]  Darwin 15.0.0
[1] npm
[1] ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "run" "electron"
[1] npm ERR!
[1] node v4.2.0
[1] npm ERR!
[1] npm
[1]  v3.3.9
[1] npm
[1] ERR! code ELIFECYCLE
[1] npm ERR! ipfs-station@1.0.0-alpha.1 electron: `electron index.js 2>&1`
[1] npm
[1]
[1] ERR! Exit status 1
[1] npm
[1] ERR!
[1] npm ERR! Failed at the ipfs-station@1.0.0-alpha.1 electron script 'electron index.js 2>&1'.
[1] npm ERR! This is most likely a problem with the ipfs-station package,
[1] npm ERR!
[1]  not with npm itself.
[1] npm ERR! Tell the author that this fails on your system:
[1] npm ERR!     electron index.js 2>&1
[1] npm ERR! You can get their info via:
[1] npm ERR!     npm owner ls ipfs-station
[1] npm ERR! There is likely additional logging output above.
[1]
[1] npm ERR! Please include the following file with any support request:
[1] npm ERR!     /Users/david/Documents/code/ipfs/station/npm-debug.log
[1] npm run electron exited with code 1
--> Sending SIGTERM to other processes..
[0] node dev-server.js exited with code null

npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "run" "start"
npm ERR! node v4.2.0
npm ERR! npm  v3.3.9
npm ERR! code ELIFECYCLE
npm ERR! ipfs-station@1.0.0-alpha.1 start: `npm run clean && npm run build:babel && ./node_modules/.bin/concurrent --kill-others "node dev-server.js" "npm run electron"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ipfs-station@1.0.0-alpha.1 start script 'npm run clean && npm run build:babel && ./node_modules/.bin/concurrent --kill-others "node dev-server.js" "npm run electron"'.
npm ERR! This is most likely a problem with the ipfs-station package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run clean && npm run build:babel && ./node_modules/.bin/concurrent --kill-others "node dev-server.js" "npm run electron"
npm ERR! You can get their info via:
npm ERR!     npm owner ls ipfs-station
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/david/Documents/code/ipfs/station/npm-debug.log
```

**Comment by Dignifiedquire** [comment] 2015-10-24 09:34
@diasdavid  :(
* Could you post the log from `app.log`
* Did this happen "randomly" or when you were doing something in the UI?
* Which version did you have checked out when this happened?
* Can you please try with the latest one (I tried improving the exception logging in there)

**Comment by Dignifiedquire** [comment] 2015-10-24 09:39
I was able to reproduce, it seems it only happens when initializing a new node and then connecting

**Comment by Dignifiedquire** [comment] 2015-10-24 09:52
This is the error I got https://gist.github.com/Dignifiedquire/dd288f9332e11ac797a6 as far as I can tell the underlying issue is a `ECONNRESET` but I don't know where it is coming from and why it's happening

**Comment by bcomnes** [comment] 2015-10-24 18:40
Fresh install, getting unresolved peer dependency issues with npm3.

```
npm WARN EPEERINVALID react-file-drop@0.1.6 requires a peer of react@^0.13 || 0.14.0-beta1 but none was installed.
```

**Comment by whyrusleeping** [comment] 2015-10-24 18:44
@bcomnes i get that every time too, but i ignored it since it was a warning.

**Comment by almereyda** [comment] 2015-11-21 03:02
Same here:

```
npm ERR! Linux 4.2.5-201.fc22.x86_64
npm ERR! argv "/home/almereyda/.nvm/versions/node/v4.2.2/bin/node" "/home/almereyda/.nvm/versions/node/v4.2.2/bin/npm" "start"
npm ERR! node v4.2.2
npm ERR! npm  v3.4.1
npm ERR! code ELIFECYCLE
npm ERR! ipfs-station@1.0.0-alpha.1 start: `concurrent --kill-others 'node dev-server.js' 'npm run electron'`
npm ERR! Exit status 1
```

with electron, rimraf and babel globally installed. Worked also with soley electron-prebuit installed, too.
Is

```
[1] info: Starting tray
[1] error: Uncaught Exception: Cannot read property 'Hash' of undefined [TypeError: Cannot read property 'Hash' of undefined] TypeError: Cannot read property 'Hash' of undefined
[1]     at /home/almereyda/Fundus/github.com/ipfs/station/node_modules/ipfs-geoip/lib/lookup.js:25:58
[1]     at /home/almereyda/Fundus/github.com/ipfs/station/node_modules/ipfs-api/src/request-api.js:52:7
[1]     at finish (/home/almereyda/Fundus/github.com/ipfs/station/node_modules/wreck/lib/index.js:294:20)
[1]     at wrapped (/home/almereyda/Fundus/github.com/ipfs/station/node_modules/hoek/lib/index.js:867:20)
[1]     at onReaderFinish (/home/almereyda/Fundus/github.com/ipfs/station/node_modules/wreck/lib/index.js:365:16)
[1]     at g (events.js:260:16)
[1]     at emitNone (events.js:72:20)
[1]     at emit (events.js:166:7)
[1]     at finishMaybe (_stream_writable.js:468:14)
[1]     at afterWrite (_stream_writable.js:347:3) { '0': [TypeError: Cannot read property 'Hash' of undefined] }
[1] info: Shutting down application
```

maybe also worth a new issue? Querying for `hash` didn't reveal an existing one.

**Comment by Dignifiedquire** [comment] 2015-12-20 09:24
Please try again with latest `master`.

**Comment by almereyda** [comment] 2015-12-21 17:41
Confirmed for Node 5.3.0 + npm latest + clean cache.
No success with Node 4.2.3 + npm latest.

always rm -rf'ed the node_modules
on Fedora 22, GNU/Linux 4.2.6

**Comment by Dignifiedquire** [comment] 2015-12-21 17:45
@almereyda what do you mean with "confirmed for node 5.3.0", that the same issue exists or that it works? 
And what does not work on node 4?

**Comment by almereyda** [comment] 2015-12-21 19:27
Just closed the tabs for the node 4 one: some `Z_BUF_ERROR` unzip error in tgz `tar.unpack`.
Was about to send a tweet regarding the increased availability of ipfs station for Fedora and probably others, linking back to this conversation.

**Comment by hacdias** [comment] 2017-12-01 23:16
I think we should close this because this doesn't happen anymore. /cc @diasdavid

**Closed by hacdias** 2017-12-01 23:17 UTC

**Comment by diasdavid** [comment] 2017-12-02 06:30
Woot! thank you @hacdias !! :)
